/**
 * Writes src/lib/publicImages.ts from the contents of public/.
 *
 * The list is generated at build time rather than read with fs at request time,
 * because public/ is not guaranteed to exist in the serverless bundle on Vercel.
 * Runs automatically via the `prebuild` script.
 *
 *   npm run gen:images
 */
import { readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const IMAGE_PATTERN = /\.(png|jpe?g|gif|webp|avif|svg)$/i;

/** Interface chrome, not activity artwork: excluded from cover suggestions. */
const UI_ASSETS = new Set([
  "adm-login.png",
  "avatar.png",
  "close.png",
  "closedEye.png",
  "create.png",
  "delete.png",
  "filter.png",
  "home.png",
  "home_background.png",
  "login_background.png",
  "logo.png",
  "logo_tlp.png",
  "logout.png",
  "openEye.png",
  "search.png",
  "sort.png",
  "teacher-login.png",
  "update.png",
]);

const publicDir = resolve(process.cwd(), "public");
const target = resolve(process.cwd(), "src/lib/publicImages.ts");

const files = readdirSync(publicDir)
  .filter((file) => IMAGE_PATTERN.test(file) && !UI_ASSETS.has(file))
  .sort((a, b) => a.localeCompare(b, "pt-BR"));

const contents = `// Generated by scripts/generate-public-images.ts. Do not edit by hand.
// Run \`npm run gen:images\` after adding files to public/.

export const PUBLIC_IMAGES: string[] = [
${files.map((file) => `  ${JSON.stringify(`/${file}`)},`).join("\n")}
];
`;

writeFileSync(target, contents);
console.log(`Wrote ${files.length} image paths to src/lib/publicImages.ts`);
